"""empty message

Revision ID: 05b5caa08a0d
Revises: 15f44607c388
Create Date: 2025-05-23 09:36:04.389290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b5caa08a0d'
down_revision = '15f44607c388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wheather', sa.String(length=120), nullable=False))
        batch_op.drop_column('wheater')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wheater', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('wheather')

    # ### end Alembic commands ###
