"""empty message

Revision ID: 3400d790db64
Revises: 05b5caa08a0d
Create Date: 2025-05-23 09:36:44.280942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3400d790db64'
down_revision = '05b5caa08a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather', sa.String(length=120), nullable=False))
        batch_op.drop_column('wheather')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wheather', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('weather')

    # ### end Alembic commands ###
